# 1. How to build gconcord python package

### Step 1: Prepare for the following files:

 - core.cpp, core.h
 - wrap.cpp, wrap.h
 
### Step 2: Run the following command in the terminal to generate a shared library.

In [ ]:
# g++ -fPIC -I/home/jovyan/Supportpkgs/eigen-3.37/ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"build/core.d" -MT"build/core.o" -o "build/core.o" "src/core.cpp"
# g++ -fPIC -I/home/jovyan/Supportpkgs/eigen-3.37/ -I/opt/conda/pkgs/python-3.7.3-h5b0a415_0/include/python3.7m/ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"build/wrap.d" -MT"build/wrap.o" -o "build/wrap.o" "src/wrap.cpp"
# g++ -shared -o "gconcord/sharedlib.so"  build/core.o build/wrap.o
# python setup.py install
# python


Make sure that the header includes:
 #include <Eigen/Core>
 #include <Eigen/Dense>
 #include <Eigen/Sparse>

### Step 3: Write \_\_init\_\_.py file and gconcord.py file

### Step 4: Write setup.py file

### Step 5: Run setup.py file to install the package in the shell: python setup.py install.

### (Optional) Step 6: Pack the files by *zip -r my_arch.zip my_folder* or *tar -cvzf my_arch.tar.gz my_folder*.

# 2. A demo for gconcord module

In [1]:
import numpy as np
import numpy.ctypeslib as npct
import site
import os.path
import sys
from ctypes import c_int, c_double

lam1 = 0.2
lam2 = 0.1
p = 6

mean = [0 for i in range(p)]
cov = np.diag(np.random.uniform(1, 2, p))
x = np.random.multivariate_normal(mean, cov, 30)

S = np.cov(x, rowvar =  False)

from gconcord import gconcord
omega = gconcord.gconcord(S, lam1, lam2)
omega.round(3)

array([[ 0.884,  0.   ,  0.   ,  0.   , -0.013,  0.   ],
       [ 0.   ,  0.512,  0.   ,  0.   ,  0.079,  0.11 ],
       [ 0.   ,  0.   ,  0.522,  0.   ,  0.   , -0.021],
       [ 0.   ,  0.   ,  0.   ,  0.495,  0.   ,  0.   ],
       [-0.013,  0.079,  0.   ,  0.   ,  0.677,  0.05 ],
       [ 0.   ,  0.11 , -0.021,  0.   ,  0.05 ,  0.567]])

In [22]:
import numpy as np
from gconcord import gconcord
x = np.array([[-0.57299987, -1.22881728,  0.24802264,  0.59779037,  0.65240208, 0.89373708],
              [ 0.84087632, -0.3383771 ,  0.0794175 ,  0.12716686, -0.97403288,-0.30804861],
              [ 0.13180135, -0.35350249,  0.01601294,  0.30258641,  0.19927309, 0.95847883],
              [ 0.44658609,  0.12839939, -2.36179304, -3.2224078 , -0.92297796,-1.55831917],
              [-1.00001779, -0.08302829,  0.6814525 ,  0.31812938, -0.50994963,-0.39614266],
              [-0.3653738 , -0.20899641,  0.33488842,  0.93276311,  0.18263188,-1.58771894],
              [ 0.53065032, -0.61604128, -0.67789621,  0.48183976,  0.20767173, 0.20307444],
              [-0.13368724, -0.12181896, -0.52881865, -0.91883273, -0.35672818,-0.09414685],
              [-1.23926047, -0.02615426, -1.02995135, -0.99250009, -0.89672846,-0.54350656],
              [-0.97725987, -0.95743644, -0.47911092, -0.22157924,  1.8751929 , 1.04114063],
              [ 1.4149165 ,  0.93326499, -0.09200369,  0.03342898,  1.71023076, 1.82671778],
              [ 0.19710653, -0.94066402, -1.15043928,  0.88932662,  0.3247554 ,-0.87942537]])   
S = np.cov(x, rowvar =  False)
omega = gconcord.gconcord(S, 0.2, 0.05, method = "ista")
omega.round(6)

array([[ 1.521808, -0.428711,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.428711,  3.076337,  0.      ,  0.283424,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  1.774255, -0.670256,  0.      , -0.100537],
       [ 0.      ,  0.283424, -0.670256,  0.956787, -0.094546,  0.      ],
       [ 0.      ,  0.      ,  0.      , -0.094546,  1.29497 , -0.536385],
       [ 0.      ,  0.      , -0.100537,  0.      , -0.536385,  1.026583]])

# 3. A demo for graphical_concord_ module

In [3]:
from gconcord.graphical_concord_ import GraphicalConcord, GraphicalConcordCV

model = GraphicalConcord(lam1 = 0.2, lam2 = 0.05)
ans = model.fit(x)
ans.omega.round(6)

array([[ 1.521808, -0.428711,  0.      ,  0.      ,  0.      ,  0.      ],
       [-0.428711,  3.076337,  0.      ,  0.283426,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  1.774256, -0.670263,  0.      , -0.100538],
       [ 0.      ,  0.283426, -0.670263,  0.956788, -0.094547,  0.      ],
       [ 0.      ,  0.      ,  0.      , -0.094547,  1.294968, -0.536387],
       [ 0.      ,  0.      , -0.100538,  0.      , -0.536387,  1.026582]])

In [30]:
cv = GraphicalConcordCV(method = "fista")
res = cv.fit(x)

In [28]:
ans.lam1

0.16077637940881462

In [29]:
ans.lam2

2.531320315688186

In [31]:
np.sum(abs(np.array([round(res.lam1,6) - 0.160776, round(res.lam2,6) - 2.531320])))

0.0